//exclude - by using <exclude> tag
//we need to mention the group id and artifact id of the dependency you wish to exclude
//in exclusion tags

//<exclusions>
//<exclusion>
//	<artifactId> hamcrest -core</artifact-id>
//		<groupId>org.hamcrest</groupID>
//			</Exclusion>
//			</Exclusions>

//settings.xml : it is a file, that maintains and holds config of mvn proj

//mvn depenency - jar file
//artifact- something used or produced by the proj. mvn proj usually has 1 artifact
//repository -its a location on a file s/m where maven artfact is stored and managed


//sequence mvn searches for dependency libs - local, central, remote, if not foundin these 
//repos, throws an error

// maven - open src biuld tool
//allows devs to buils and document lifecycle f/w
//used for proj build as well as managing dependencies and docmentn
//used to create and manage any java based proj

//run testclasses - sure fire plugin - can use to specify test classes or methods we want 
//to execute

//build phases - Validate, Compile,Test,Package,Verify,Install,Deploy

//ANT- toolox, build tool, scripts are not reusable, no lifecycle, less preferred

//Maven- build+Proj mgmt tool, has lifecycle f/w, more preferred, scripts are reusable

//POM - XML file that contains info abt proj and config used by mvn to build the proj.
//fundamental unit of work in mvn
//contains default values for most projs

//Extrnl dpncies can be configd in pm.xml by specifying groupid, artifact id and scope as
//s/m, have to specify s/m path relative to the proj excn.

//local repo- is a dir on the comp where mvn stores all the proj artifacts
//Github is local repo


//mvn build LC
//Default - creating build and deploying. VCTPVID
//clean- cleans the  proj and removes all files generated by the previos build
//suite - creation of documentation

//how did you use maven in your proj
//Configure Maven in Java, using Project Object Model (POM) found in a pom. xml file.
//All Maven-related configuration settings are found in the POM. ...
//Maven provides default settings for configurations, so you don't have to add every 
//configuration into the pom.








